language: python
python:
  - 3.6

addons:
  apt:
    packages: &common_packages
      - gfortran
      - libatlas-dev
      - libatlas-base-dev

bundler_args: --retry 3

install:
  - travis_retry travis_wait pip install -r requirements.txt
  - pip install pytest-cov
  - pip install codecov
  - pip install tox

script:
  - python tools/travis/run.py

after_success:
  - codecov

notifications:
  email: false
