language: python
python:
  - 2.7
  - 3.0
  - 3.1
  - 3.2
  - 3.3
  - 3.4
  - 3.5

addons:
  apt:
    packages: &common_packages
      - gfortran
      - libatlas-dev
      - libatlas-base-dev
bundler_args: --retry 3

before_install:
  - pip install codecov

install: travis_retry travis_wait pip install -r requirements.txt

script:  python travis-ci/run.py

after_success:
  - codecov


