language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

addons:
  apt:
    packages: &common_packages
      - gfortran
      - libatlas-dev
      - libatlas-base-dev

bundler_args: --retry 3

install:
  - travis_retry travis_wait pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov

script:
  - travis_wait pytest --cov=respy

after_success:
  - codecov

notifications:
  slack: policy-lab:LkWqVb15dNvdLjMQOyacTXy6
  email: false

