language:
    - python

python:
    - 3.6

before_install:
    - sudo apt-get update

addons:
    apt:
        packages:
            - gfortran
            - libatlas-dev
            - libatlas-base-dev

matrix:
    include:
        - env: TRAVIS_CI_FORTRAN=False TRAVIS_CI_MPI=False  TRAVIS_CI_OMP=False
        - env: TRAVIS_CI_FORTRAN=True TRAVIS_CI_MPI=True  TRAVIS_CI_OMP=True
        - env: TRAVIS_CI_FORTRAN=True TRAVIS_CI_MPI=False TRAVIS_CI_OMP=True
        - env: TRAVIS_CI_FORTRAN=True TRAVIS_CI_MPI=True  TRAVIS_CI_OMP=False

bundler_args: --retry 3

install:
    - sudo apt-get install -y -q mpich libmpich-dev
    - sudo apt-get install -y -q openmpi-bin libopenmpi-dev
    - travis_retry travis_wait pip install -r requirements.txt
    - pip install -e . -vv
    - pip install pytest-cov
    - pip install codecov

script:
    - travis_wait 30 pytest --cov=respy --vvv -s

after_success:
    - codecov

notifications:
    email: false
