language: python
python:
  - 3.6

addons:
  apt:
    packages: &common_packages
      - gfortran
      - libatlas-dev
      - libatlas-base-dev

env:

  - TRAVIS_CI_DEBUG=False
  - TRAVIS_CI_DEBUG=True

  - TRAVIS_CI_FORTRAN=False
  - TRAVIS_CI_FORTRAN=True

  - TRAVIS_CI_F2PY=False
  - TRAVIS_CI_F2PY=True

bundler_args: --retry 3

install:
    - apt-get install -y -q mpich libmpich-dev
    - travis_retry travis_wait pip install -r requirements.txt
    - pip install -e . -vv
    - pip install pytest-cov
    - pip install codecov

script:
  - travis_wait 30 pytest --cov=respy

after_success:
  - codecov

notifications:
  slack: policy-lab:LkWqVb15dNvdLjMQOyacTXy6
  email: false
