# Development Notes:
#
#   1) For some reason tox fails for py34. We should revisit this each time we work on upgrades to this script.
#

language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

addons:
  apt:
    packages: &common_packages
      - gfortran
      - libatlas-dev
      - libatlas-base-dev
      - libcr-dev
      - mpich2
      - mpich2-doc

bundler_args: --retry 3

install:
  - travis_retry travis_wait pip install -r requirements.txt
  - pip install codecov
  - pip install tox

script:
  - python setup.py develop
  - travis_wait tox -e py27 -v
  - travis_wait tox -e py35 -v
  - travis_wait tox -e py36 -v
  - python tools/travis/run.py

after_success:
  - codecov

notifications:
  slack: policy-lab:LkWqVb15dNvdLjMQOyacTXy6
  email: false
