language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

addons:
  apt:
    packages: &common_packages
      - gfortran
      - libatlas-dev
      - libatlas-base-dev

bundler_args: --retry 3

install:
  - travis_retry travis_wait pip install -r requirements.txt
  - pip install codecov
  - pip install tox
script:
  - travis_wait tox -e py27 -v
  - travis_wait tox -e py34 -v
  - travis_wait tox -e py35 -v
  - python tools/travis_run.py

after_success:
  - codecov

notifications:
  slack: policy-lab:LkWqVb15dNvdLjMQOyacTXy6
  email: false
